# Generated by Django 2.2 on 2020-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_orderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
