# Generated by Django 2.2 on 2020-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200129_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
