# Generated by Django 2.2 on 2020-02-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
